# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pokes',
            field=models.IntegerField(default=0),
        ),
    ]
